export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_BURGER = 'INIT_BURGER';

export const PURCHASE_BURGER_SUCCESS  = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAIL  = "PURCHASE_BURGER_FAIL"
export const PURCHAE_INIT = "PURCHAE_INIT"

export const ORDER_SUCCESS  ="ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL  = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";